baseURL = "https://penang.eden.my/"
languageCode = "en-uk"
title = "Eden"
theme = "ezhil"
copyright = "© Copyright Inspire My 2019"
paginate = 10
disqusShortname = "localhost"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
baseBoxURL = "https://box.eden.my"
subtitle = "Penang Botanic Gardens Plant Collection"
mainSections = ["plants"]
disableDisqusTypes = ["page", "section", "home"]

[params.algolia]
vars = ["family", "species", "genus", "sp1", "author1", "rank1", "sp2", "author2", "vernacular", "ecology", "distribution", "uses"]
params = []

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All plants"
url = "/plants"
weight = 2

[outputs]
page = ["HTML", "json"]
section = ["HTML", "json"]
home = ["HTML", "Algolia", "json"]
