baseURL = "https://penang.eden.my/"
languageCode = "en-uk"
title = "Eden"
theme = "ezhil"
copyright = "© Copyright Inspire My 2019"
paginate = 10
disqusShortname = "localhost"

[params]
  baseBoxURL = "https://box.eden.my"
  subtitle = "Penang Botanic Gardens Plant Collection"
  mainSections = ["plants"]
  disableDisqusTypes = ["page", "section", "home"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All plants"
url = "/plants"
weight = 2

[outputs]
  page = ["json", "HTML"]
  section = ["json", "HTML"]
  home = ["json", "HTML"]
