---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/plants
  label: Plants
  create: all
  match: "**/*"
upload_dir: media
public_path: https://ap-southeast-1.amazonaws.com/eden-penang-box
front_matter_path: "/media"
use_front_matter_path: true
file_template: ":year:-:month:-:day:-:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
